{
 "title": "7-8 Copy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU replica",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"postgres-2\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU MASTER",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"postgres-1\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication LAG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "pg_replication_lag_seconds", "legendFormat": "__auto" }
   ]
  }
 ]
}